name: planet-notebooks
channels:
  - conda-forge
  - pyviz/label/dev
  - anaconda
  - defaults
dependencies:
  - affine=2.2.2=py36_0
  - appnope=0.1.0=py36hf537a9a_0
  - asn1crypto=0.24.0=py36_0
  - atomicwrites=1.3.0=py36_1
  - attrs=19.1.0=py36_1
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - bokeh=1.1.0rc1=py_0
  - branca=0.3.1=py_0
  - bzip2=1.0.6=h1de35cc_5
  - ca-certificates=2019.3.9=hecc5488_0
  - cairo=1.14.12=hc4e6be7_4
  - cartopy=0.17.0=py36haea56ea_1
  - certifi=2019.3.9=py36_0
  - cffi=1.12.2=py36hb5b8e2f_1
  - cftime=1.0.3.4=py36h1d22016_0
  - chardet=3.0.4=py36_1
  - click=7.0=py36_0
  - click-plugins=1.0.4=py36_0
  - cligj=0.5.0=py36_0
  - cloudpickle=0.8.0=py36_0
  - colorcet=2.0.1=py_0
  - cryptography=2.6.1=py36ha12b0ac_0
  - curl=7.64.0=ha441bb4_2
  - cycler=0.10.0=py36hfc81398_0
  - cytoolz=0.9.0.1=py36h1de35cc_1
  - dask=1.1.4=py36_1
  - dask-core=1.1.4=py36_1
  - datashader=0.7.0=py_0
  - datashape=0.5.4=py36_1
  - dbus=1.13.6=h90a0687_0
  - decorator=4.4.0=py36_1
  - defusedxml=0.5.0=py36_1
  - descartes=1.1.0=py36_0
  - distributed=1.26.0=py36_1
  - entrypoints=0.3=py36_0
  - expat=2.2.6=h0a44026_0
  - fastparquet=0.2.1=py36h1d22016_1
  - fiona=1.8.4=py36h9a122fd_0
  - fontconfig=2.13.0=h5d5b041_1
  - freetype=2.9.1=hb4e5f40_0
  - freexl=1.0.5=h1de35cc_0
  - futures-compat=1.0=py3_0
  - gdal=2.3.3=py36hbe65578_0
  - geojson=2.4.1=py_0
  - geopandas=0.4.1=py_0
  - geos=3.7.1=h0a44026_0
  - geoviews=1.6.3a2=py_0
  - geoviews-core=1.6.3a2=py_0
  - gettext=0.19.8.1=h15daf44_3
  - giflib=5.1.4=h1de35cc_1
  - glib=2.56.2=hd9629dc_0
  - hdf4=4.2.13=h39711bb_2
  - hdf5=1.10.4=hfa1e0ec_0
  - heapdict=1.0.0=py36_2
  - holoviews=1.12.0=py_0
  - hvplot=0.4.0=py_0
  - icu=58.2=h4b95b61_1
  - idna=2.8=py36_0
  - imageio=2.5.0=py36_0
  - intel-openmp=2019.3=199
  - ipykernel=5.1.0=py36h39e3cac_0
  - ipyleaflet=0.10.1=py36_0
  - ipython=7.1.1=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36h241746c_0
  - ipywidgets=7.4.2=py36_0
  - jedi=0.13.3=py36_0
  - jinja2=2.10=py36_0
  - jpeg=9b=he5867d9_2
  - jsanimation=0.1=py_1
  - json-c=0.13.1=h3efe00b_0
  - jsonschema=3.0.1=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.2.4=py36_0
  - jupyter_console=6.0.0=py36_0
  - jupyter_core=4.4.0=py36_0
  - kealib=1.4.7=hf5ed860_6
  - kiwisolver=1.0.1=py36h0a44026_0
  - krb5=1.16.1=hddcf347_7
  - libboost=1.67.0=hebc422b_4
  - libcurl=7.64.0=h051b688_2
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libdap4=3.19.1=h3d3e54a_0
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgdal=2.3.3=h0950a36_0
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libkml=1.3.0=hbe12b63_4
  - libnetcdf=4.6.1=hd5207e6_2
  - libpng=1.6.36=ha441bb4_0
  - libpq=11.2=h051b688_0
  - libsodium=1.0.16=h3efe00b_0
  - libspatialindex=1.8.5=h2c08c6b_2
  - libspatialite=4.3.0a=h644ec7d_19
  - libssh2=1.8.0=ha12b0ac_4
  - libtiff=4.0.10=hcb84e12_2
  - libxml2=2.9.9=hab757c2_0
  - libxslt=1.1.33=h33a18ac_0
  - llvmlite=0.28.0=py36h8c7ce04_0
  - locket=0.2.0=py36hca03003_1
  - lxml=4.3.2=py36hef8c89e_0
  - mapclassify=2.0.1=py_0
  - markdown=3.0.1=py36_0
  - markupsafe=1.1.1=py36h1de35cc_0
  - matplotlib=3.0.3=py36h54f8f79_0
  - mistune=0.8.4=py36h1de35cc_0
  - mkl=2019.3=199
  - mkl_fft=1.0.10=py36h5e564d8_0
  - mkl_random=1.0.2=py36h27c97d8_0
  - more-itertools=6.0.0=py36_0
  - msgpack-python=0.6.1=py36h04f5b5a_1
  - multipledispatch=0.6.0=py36_0
  - munch=2.3.2=py36_0
  - nbconvert=5.4.1=py36_3
  - nbformat=4.4.0=py36h827af21_0
  - ncurses=6.1=h0a44026_1
  - netcdf4=1.4.2=py36h13743db_0
  - networkx=2.2=py36_1
  - notebook=5.7.8=py36_0
  - numba=0.43.1=py36h6440ff4_0
  - olefile=0.46=py36_0
  - openjpeg=2.3.0=hb95cd4c_1
  - openssl=1.1.1b=h01d97ff_2
  - owslib=0.17.1=py_0
  - packaging=19.0=py36_0
  - pandas=0.24.2=py36h0a44026_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - panel=0.5.0=py_0
  - param=1.9.0=py_0
  - parso=0.3.4=py36_0
  - partd=0.3.10=py36_1
  - pcre=8.43=h0a44026_0
  - pexpect=4.6.0=py36_0
  - phantomjs=2.1.1=0
  - pickleshare=0.7.5=py36_0
  - pillow=5.4.1=py36hb68e598_0
  - pip=19.0.3=py36_0
  - pixman=0.38.0=h1de35cc_0
  - pluggy=0.9.0=py36_0
  - poppler=0.65.0=ha097c24_1
  - poppler-data=0.4.9=0
  - proj4=5.2.0=h0a44026_1
  - prometheus_client=0.6.0=py36_0
  - prompt_toolkit=2.0.9=py36_0
  - psutil=5.6.1=py36h1de35cc_0
  - psycopg2=2.7.6.1=py36ha12b0ac_0
  - ptyprocess=0.6.0=py36_0
  - py=1.8.0=py36_0
  - pycparser=2.19=py36_0
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pyepsg=0.4.0=py36_0
  - pygments=2.3.1=py36_0
  - pykdtree=1.3.1=py36h1d22016_2
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.3.1=py36_0
  - pyproj=1.9.6=py36h9c430a6_0
  - pyqt=5.9.2=py36h655552a_2
  - pyrsistent=0.14.11=py36h1de35cc_0
  - pyshp=2.0.1=py36_0
  - pysocks=1.6.8=py36_0
  - pytest=4.3.1=py36_0
  - python=3.6.8=haf84260_0
  - python-dateutil=2.8.0=py36_0
  - python-snappy=0.5.3=py36h0a44026_0
  - pytz=2018.9=py36_0
  - pyviz=0.10.0=py_0
  - pyviz_comms=0.7.2=py_0
  - pywavelets=1.0.2=py36h1d22016_0
  - pyyaml=5.1=py36h1de35cc_0
  - pyzmq=18.0.0=py36h0a44026_0
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.4.3=py36_0
  - readline=7.0=h1de35cc_5
  - requests=2.21.0=py36_0
  - rise=5.3.0=py36_0
  - rtree=0.8.3=py36_0
  - scikit-image=0.14.2=py36h0a44026_0
  - scipy=1.2.1=py36h1410ff5_0
  - selenium=3.141.0=py36h1de35cc_0
  - send2trash=1.5.0=py36_0
  - setuptools=40.8.0=py36_0
  - shapely=1.6.4=py36he8793f5_0
  - sip=4.19.8=py36h0a44026_0
  - six=1.12.0=py36_0
  - snappy=1.1.7=he62c110_3
  - snuggs=1.4.3=py_0
  - sortedcontainers=2.1.0=py36_0
  - sqlalchemy=1.3.1=py36h1de35cc_0
  - sqlite=3.27.2=ha441bb4_0
  - streamz=0.5.0=py36_0
  - tblib=1.3.2=py36hda67792_0
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36h625a49b_0
  - thrift=0.11.0=py36h0a44026_0
  - tk=8.6.8=ha441bb4_0
  - toolz=0.9.0=py36_0
  - tornado=5.1.1=py36h1de35cc_0
  - tqdm=4.31.1=py_0
  - traitlets=4.3.2=py36h65bd3ce_0
  - traittypes=0.2.1=py_1
  - urllib3=1.24.1=py36_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - webencodings=0.5.1=py36_1
  - wheel=0.33.1=py36_0
  - widgetsnbextension=3.4.2=py36_0
  - xarray=0.11.3=py36_0
  - xerces-c=3.2.2=h44e365a_0
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zeromq=4.3.1=h0a44026_3
  - zict=0.1.4=py36_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
  - pip:
    - geojsonio==0.0.3
    - github3-py==1.3.0
    - jwcrypto==0.6.0
    - numpy==1.14.6
    - opencv-python==3.3.0.10
    - planet==1.2.2
    - rasterio==1.0.9
    - requests-futures==0.9.9
    - scikit-learn==0.20.3
    - uritemplate==3.0.0
prefix: /anaconda3/envs/pyviz